import { useState, useRef } from 'react';
import type { NextPageWithLayout } from '@/types';
import cn from 'classnames';
import dynamic from 'next/dynamic';
import { NextSeo } from 'next-seo';
import Button from '@/components/ui/button';
import CoinInput from '@/components/ui/coin-input';
import TransactionInfo from '@/components/ui/transaction-info';
import { SwapIcon } from '@/components/icons/swap-icon';
import DashboardLayout from '@/layouts/_dashboard';
import Trade from '@/components/ui/trade';
import { setup1inchWidget } from '@1inch/embedded-widget';

import { useSendTransaction, useAccount } from 'wagmi';

const SwapPage: NextPageWithLayout = () => {
  const { address, isConnecting, isDisconnected } = useAccount();

  if (isDisconnected) return <div>Disconnected - Please Connect Wallet</div>;

  return (
    <>
      <NextSeo
        title="Farms"
        description="TikToken Web3 Dapp allows users to earn TT2E BSC tokens while using TikTok Social Network. The more TT2E Camera NFTs users own, the more they will maximise the earnings generated by their TikTok content"
      />

      <div className="mb-5 border-b border-dashed border-gray-200 pb-5 dark:border-gray-800 xs:mb-7 xs:pb-6">
        <iframe
          src="https://pancakeswap.finance/swap?outputCurrency=0x24A8EB1b906bB10d79351d4A65AbEd56baFa0B0f"
          frameBorder="0"
          width="800"
          height="900"
        ></iframe>
      </div>
    </>
  );
};

SwapPage.getLayout = function getLayout(page) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default SwapPage;
